[project]
name = "TUX"
version = "1.1"
description = "TUX scripts pour Ubuntu"
authors = [
  {name = "Jérôme Quintard", email = "jquintard@yeraz.fr"}
]
dependencies = []

[project.scripts]
# motd = "motd.motd:main"

[tool.setuptools]
package-dir = {"" = "src"}